routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->middleware('verified');


Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
)->name('io_generator_builder_generate_from_file');

Route::resource('countries', 'CountryController');



Route::resource('provinces', 'ProvinceController');

Route::resource('cities', 'CityController');

Route::resource('municipalities', 'MunicipalityController');

Route::resource('neighborhoods', 'NeighborhoodController');

Route::resource('accounts', 'AccountController');

Route::resource('taxes', 'TaxController');

Route::resource('statuses', 'StatusController');

Route::resource('propertyTypes', 'Property_typeController');

Route::resource('properties', 'PropertyController');

Route::resource('currencies', 'CurrencyController');

Route::resource('expenses', 'ExpenseController');

Route::resource('transactionTypes', 'Transaction_typeController');

Route::resource('publications', 'PublicationController');

Route::resource('images', 'ImageController');



Route::resource('transactions', 'TransactionController');

Route::resource('features', 'FeatureController');

app/Models/Transaction_type.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Transaction_type extends Model
{
    use SoftDeletes;

    public $table = 'transaction_types';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'name',
        'slug'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'slug' => 'string',

    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function transactions()
    {
        return $this->hasMany(\App\Models\Transaction::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function publications()
    {
        return $this->belongsToMany(\App\Models\Publication::class,'publications_transaction_types' )
        ->using(\App\Models\PublicationsTransactionTypes::class)
        ->withPivot('price','currency_id');
    }


    /////////////////////////////
    ///SCOPES
    /////////////////////////////

    public function scopeFilter($query, $filter)
    {
        if ($filter)
            return $query
                ->orWhere('name', "LIKE", '%' . $filter . '%');
    }

}

resources/views/transactions/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Transaction
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'transactions.store']) !!}

                        @include('transactions.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/transactions/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Transaction
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($transaction, ['route' => ['transactions.update', $transaction->id], 'method' => 'patch']) !!}

                        @include('transactions.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/transactions/fields.blade.php
<!-- User Owner Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('user_owner_id', 'User Owner Id:') !!}
    {!! Form::text('user_owner_id', null, ['class' => 'form-control']) !!}
</div>

<!-- User Customer Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('user_customer_id', 'User Customer Id:') !!}
    {!! Form::text('user_customer_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Property Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('property_id', 'Property Id:') !!}
    {!! Form::text('property_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Transaction Type Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('transaction_type_id', 'Transaction Type Id:') !!}
    {!! Form::text('transaction_type_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Value Field -->
<div class="form-group col-sm-6">
    {!! Form::label('value', 'Value:') !!}
    {!! Form::text('value', null, ['class' => 'form-control']) !!}
</div>

<!-- Currency Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('currency_id', 'Currency Id:') !!}
    {!! Form::text('currency_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('transactions.index') }}" class="btn btn-default">Cancel</a>
</div>

resources/views/transactions/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Transactions</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('transactions.create') }}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('transactions.table')
            </div>
        </div>
        <div class="text-center">
        
        @include('adminlte-templates::common.paginate', ['records' => $transactions])

        </div>
    </div>
@endsection

resources/views/transactions/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Transaction
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('transactions.show_fields')
                    <a href="{{ route('transactions.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/transactions/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{{ $transaction->id }}</p>
</div>

<!-- User Owner Id Field -->
<div class="form-group">
    {!! Form::label('user_owner_id', 'User Owner Id:') !!}
    <p>{{ $transaction->user_owner_id }}</p>
</div>

<!-- User Customer Id Field -->
<div class="form-group">
    {!! Form::label('user_customer_id', 'User Customer Id:') !!}
    <p>{{ $transaction->user_customer_id }}</p>
</div>

<!-- Property Id Field -->
<div class="form-group">
    {!! Form::label('property_id', 'Property Id:') !!}
    <p>{{ $transaction->property_id }}</p>
</div>

<!-- Transaction Type Id Field -->
<div class="form-group">
    {!! Form::label('transaction_type_id', 'Transaction Type Id:') !!}
    <p>{{ $transaction->transaction_type_id }}</p>
</div>

<!-- Value Field -->
<div class="form-group">
    {!! Form::label('value', 'Value:') !!}
    <p>{{ $transaction->value }}</p>
</div>

<!-- Currency Id Field -->
<div class="form-group">
    {!! Form::label('currency_id', 'Currency Id:') !!}
    <p>{{ $transaction->currency_id }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $transaction->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $transaction->updated_at }}</p>
</div>

resources/views/transactions/table.blade.php
<div class="table-responsive">
    <table class="table" id="transactions-table">
        <thead>
            <tr>
                <th>User Owner Id</th>
        <th>User Customer Id</th>
        <th>Property Id</th>
        <th>Transaction Type Id</th>
        <th>Value</th>
        <th>Currency Id</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($transactions as $transaction)
            <tr>
                <td>{{ $transaction->user_owner_id }}</td>
            <td>{{ $transaction->user_customer_id }}</td>
            <td>{{ $transaction->property_id }}</td>
            <td>{{ $transaction->transaction_type_id }}</td>
            <td>{{ $transaction->value }}</td>
            <td>{{ $transaction->currency_id }}</td>
                <td>
                    {!! Form::open(['route' => ['transactions.destroy', $transaction->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('transactions.show', [$transaction->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{{ route('transactions.edit', [$transaction->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>